package jet.travels.transportManager.model;
// Generated Apr 1, 2019 2:58:47 PM by Hibernate Tools 5.0.6.Final

import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * TransportVehiclerequesitions generated by hbm2java
 */
@Entity
@Table(name = "transport_vehiclerequesitions", catalog = "transportmanager")
public class TransportVehiclerequesitions implements java.io.Serializable {
	private byte[] idVehicleRequesitions;
	@JsonBackReference
	private TransportDriverguidemaster transportDriverguidemasterByIdGuide;
	@JsonBackReference
	private TransportDriverguidemaster transportDriverguidemasterByIdDriver;
	@JsonBackReference
	private TransportStatus transportStatusByRequestStatus;
	@JsonBackReference
	private TransportStatus transportStatusByStatus;
	@JsonBackReference
	private TransportStatus transportStatusByApproveStatus;
	@JsonBackReference
	private TransportStatus transportStatusByConfirmed;
	private long requisitionNo;
	private String uuid;
	private String tourId;
	private Date requestedDate;
	private String requestedBy;
	private String requestedMarket;
	private Date lastUpdateDate;
	private String lastUpdateBy;
	private String clientName;
	private String noOfAdults;
	private String noOfChild;
	private String arrivalFlightNo;
	private Date arrivalFlightTime;
	private String departureFlightNo;
	private Date departureFightTime;
	private String pickUpTime;
	private Date reportDateTime;
	private String reportTo;
	private byte[] remarks;
	private String requestedVehicle;
	private String vehicleId;
	private String requisitionType;
	private String waterBottle;
	private String waterBottleAmount;
	private String simCard;
	private String simAmount;
	private String garland;
	private String garlandAmount;
	private String dropPlace;
	private String tourNo;
	private String recordOwner;
	private String trconfirmationUuid;
	private String requestedMarketLabel;
	private String arrivalAirpot;
	private String departureAirport;
	private Integer estimatedTime;
	private String reqStatus;
	private String parentId;
	private String splitBy;

	public TransportVehiclerequesitions() {
	}

	public TransportVehiclerequesitions(TransportStatus transportStatusByRequestStatus,
			TransportStatus transportStatusByStatus, TransportStatus transportStatusByApproveStatus,
			TransportStatus transportStatusByConfirmed, long requisitionNo, String tourId, Date requestedDate,
			String requestedBy, String requestedMarket, Date lastUpdateDate, String lastUpdateBy, String clientName,
			String noOfAdults, String noOfChild, String arrivalFlightNo, Date arrivalFlightTime,
			String departureFlightNo, Date departureFightTime, String pickUpTime, Date reportDateTime, String reportTo,
			byte[] remarks, String requestedVehicle, String vehicleId, String waterBottle, String waterBottleAmount,
			String simCard, String simAmount, String garland, String garlandAmount, String dropPlace, String tourNo,
			String recordOwner) {
		this.transportStatusByRequestStatus = transportStatusByRequestStatus;
		this.transportStatusByStatus = transportStatusByStatus;
		this.transportStatusByApproveStatus = transportStatusByApproveStatus;
		this.transportStatusByConfirmed = transportStatusByConfirmed;
		this.requisitionNo = requisitionNo;
		this.tourId = tourId;
		this.requestedDate = requestedDate;
		this.requestedBy = requestedBy;
		this.requestedMarket = requestedMarket;
		this.lastUpdateDate = lastUpdateDate;
		this.lastUpdateBy = lastUpdateBy;
		this.clientName = clientName;
		this.noOfAdults = noOfAdults;
		this.noOfChild = noOfChild;
		this.arrivalFlightNo = arrivalFlightNo;
		this.arrivalFlightTime = arrivalFlightTime;
		this.departureFlightNo = departureFlightNo;
		this.departureFightTime = departureFightTime;
		this.pickUpTime = pickUpTime;
		this.reportDateTime = reportDateTime;
		this.reportTo = reportTo;
		this.remarks = remarks;
		this.requestedVehicle = requestedVehicle;
		this.vehicleId = vehicleId;
		this.waterBottle = waterBottle;
		this.waterBottleAmount = waterBottleAmount;
		this.simCard = simCard;
		this.simAmount = simAmount;
		this.garland = garland;
		this.garlandAmount = garlandAmount;
		this.dropPlace = dropPlace;
		this.tourNo = tourNo;
		this.recordOwner = recordOwner;
	}

	public TransportVehiclerequesitions(TransportDriverguidemaster transportDriverguidemasterByIdGuide,
			TransportDriverguidemaster transportDriverguidemasterByIdDriver,
			TransportStatus transportStatusByRequestStatus, TransportStatus transportStatusByStatus,
			TransportStatus transportStatusByApproveStatus, TransportStatus transportStatusByConfirmed,
			long requisitionNo, String uuid, String tourId, Date requestedDate, String requestedBy,
			String requestedMarket, Date lastUpdateDate, String lastUpdateBy, String clientName, String noOfAdults,
			String noOfChild, String arrivalFlightNo, Date arrivalFlightTime, String departureFlightNo,
			Date departureFightTime, String pickUpTime, Date reportDateTime, String reportTo, byte[] remarks,
			String requestedVehicle, String vehicleId, String requisitionType, String waterBottle,
			String waterBottleAmount, String simCard, String simAmount, String garland, String garlandAmount,
			String dropPlace, String tourNo, String recordOwner, String trconfirmationUuid, String requestedMarketLabel,
			String arrivalAirpot, String departureAirport, Integer estimatedTime, String reqStatus, String parentId,
			String splitBy, Set<TransportTerminationhistory> transportTerminationhistories,
			Set<TransportNightstops> transportNightstopses, Set<TransportLogsheet> transportLogsheets) {
		this.transportDriverguidemasterByIdGuide = transportDriverguidemasterByIdGuide;
		this.transportDriverguidemasterByIdDriver = transportDriverguidemasterByIdDriver;
		this.transportStatusByRequestStatus = transportStatusByRequestStatus;
		this.transportStatusByStatus = transportStatusByStatus;
		this.transportStatusByApproveStatus = transportStatusByApproveStatus;
		this.transportStatusByConfirmed = transportStatusByConfirmed;
		this.requisitionNo = requisitionNo;
		this.uuid = uuid;
		this.tourId = tourId;
		this.requestedDate = requestedDate;
		this.requestedBy = requestedBy;
		this.requestedMarket = requestedMarket;
		this.lastUpdateDate = lastUpdateDate;
		this.lastUpdateBy = lastUpdateBy;
		this.clientName = clientName;
		this.noOfAdults = noOfAdults;
		this.noOfChild = noOfChild;
		this.arrivalFlightNo = arrivalFlightNo;
		this.arrivalFlightTime = arrivalFlightTime;
		this.departureFlightNo = departureFlightNo;
		this.departureFightTime = departureFightTime;
		this.pickUpTime = pickUpTime;
		this.reportDateTime = reportDateTime;
		this.reportTo = reportTo;
		this.remarks = remarks;
		this.requestedVehicle = requestedVehicle;
		this.vehicleId = vehicleId;
		this.requisitionType = requisitionType;
		this.waterBottle = waterBottle;
		this.waterBottleAmount = waterBottleAmount;
		this.simCard = simCard;
		this.simAmount = simAmount;
		this.garland = garland;
		this.garlandAmount = garlandAmount;
		this.dropPlace = dropPlace;
		this.tourNo = tourNo;
		this.recordOwner = recordOwner;
		this.trconfirmationUuid = trconfirmationUuid;
		this.requestedMarketLabel = requestedMarketLabel;
		this.arrivalAirpot = arrivalAirpot;
		this.departureAirport = departureAirport;
		this.estimatedTime = estimatedTime;
		this.reqStatus = reqStatus;
		this.parentId = parentId;
		this.splitBy = splitBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idVehicleRequesitions", unique = true, nullable = false)
	public byte[] getIdVehicleRequesitions() {
		return this.idVehicleRequesitions;
	}

	public void setIdVehicleRequesitions(byte[] idVehicleRequesitions) {
		this.idVehicleRequesitions = idVehicleRequesitions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGuide")
	public TransportDriverguidemaster getTransportDriverguidemasterByIdGuide() {
		return this.transportDriverguidemasterByIdGuide;
	}

	public void setTransportDriverguidemasterByIdGuide(TransportDriverguidemaster transportDriverguidemasterByIdGuide) {
		this.transportDriverguidemasterByIdGuide = transportDriverguidemasterByIdGuide;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDriver")
	public TransportDriverguidemaster getTransportDriverguidemasterByIdDriver() {
		return this.transportDriverguidemasterByIdDriver;
	}

	public void setTransportDriverguidemasterByIdDriver(
			TransportDriverguidemaster transportDriverguidemasterByIdDriver) {
		this.transportDriverguidemasterByIdDriver = transportDriverguidemasterByIdDriver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "requestStatus", nullable = false)
	public TransportStatus getTransportStatusByRequestStatus() {
		return this.transportStatusByRequestStatus;
	}

	public void setTransportStatusByRequestStatus(TransportStatus transportStatusByRequestStatus) {
		this.transportStatusByRequestStatus = transportStatusByRequestStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public TransportStatus getTransportStatusByStatus() {
		return this.transportStatusByStatus;
	}

	public void setTransportStatusByStatus(TransportStatus transportStatusByStatus) {
		this.transportStatusByStatus = transportStatusByStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approveStatus", nullable = false)
	public TransportStatus getTransportStatusByApproveStatus() {
		return this.transportStatusByApproveStatus;
	}

	public void setTransportStatusByApproveStatus(TransportStatus transportStatusByApproveStatus) {
		this.transportStatusByApproveStatus = transportStatusByApproveStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "confirmed", nullable = false)
	public TransportStatus getTransportStatusByConfirmed() {
		return this.transportStatusByConfirmed;
	}

	public void setTransportStatusByConfirmed(TransportStatus transportStatusByConfirmed) {
		this.transportStatusByConfirmed = transportStatusByConfirmed;
	}

	@Column(name = "requisitionNo", nullable = false)
	public long getRequisitionNo() {
		return this.requisitionNo;
	}

	public void setRequisitionNo(long requisitionNo) {
		this.requisitionNo = requisitionNo;
	}

	@Column(name = "uuid", length = 36)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "tourID", nullable = false, length = 36)
	public String getTourId() {
		return this.tourId;
	}

	public void setTourId(String tourId) {
		this.tourId = tourId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "requestedDate", nullable = false, length = 26)
	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	@Column(name = "requestedBy", nullable = false, length = 36)
	public String getRequestedBy() {
		return this.requestedBy;
	}

	public void setRequestedBy(String requestedBy) {
		this.requestedBy = requestedBy;
	}

	@Column(name = "requestedMarket", nullable = false, length = 36)
	public String getRequestedMarket() {
		return this.requestedMarket;
	}

	public void setRequestedMarket(String requestedMarket) {
		this.requestedMarket = requestedMarket;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastUpdateDate", nullable = false, length = 26)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "lastUpdateBy", nullable = false, length = 36)
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	@Column(name = "clientName", nullable = false, length = 100)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "noOfAdults", nullable = false, length = 11)
	public String getNoOfAdults() {
		return this.noOfAdults;
	}

	public void setNoOfAdults(String noOfAdults) {
		this.noOfAdults = noOfAdults;
	}

	@Column(name = "noOfChild", nullable = false, length = 11)
	public String getNoOfChild() {
		return this.noOfChild;
	}

	public void setNoOfChild(String noOfChild) {
		this.noOfChild = noOfChild;
	}

	@Column(name = "arrivalFlightNo", nullable = false, length = 20)
	public String getArrivalFlightNo() {
		return this.arrivalFlightNo;
	}

	public void setArrivalFlightNo(String arrivalFlightNo) {
		this.arrivalFlightNo = arrivalFlightNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "arrivalFlightTime", nullable = false, length = 26)
	public Date getArrivalFlightTime() {
		return this.arrivalFlightTime;
	}

	public void setArrivalFlightTime(Date arrivalFlightTime) {
		this.arrivalFlightTime = arrivalFlightTime;
	}

	@Column(name = "departureFlightNo", nullable = false, length = 20)
	public String getDepartureFlightNo() {
		return this.departureFlightNo;
	}

	public void setDepartureFlightNo(String departureFlightNo) {
		this.departureFlightNo = departureFlightNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "departureFightTime", nullable = false, length = 26)
	public Date getDepartureFightTime() {
		return this.departureFightTime;
	}

	public void setDepartureFightTime(Date departureFightTime) {
		this.departureFightTime = departureFightTime;
	}

	//@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pickUpTime", nullable = false, length = 26)
	public String getPickUpTime() {
		return this.pickUpTime;
	}

	public void setPickUpTime(String pickUpTime) {
		this.pickUpTime = pickUpTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reportDateTime", nullable = false, length = 26)
	public Date getReportDateTime() {
		return this.reportDateTime;
	}

	public void setReportDateTime(Date reportDateTime) {
		this.reportDateTime = reportDateTime;
	}

	@Column(name = "reportTo", nullable = false, length = 36)
	public String getReportTo() {
		return this.reportTo;
	}

	public void setReportTo(String reportTo) {
		this.reportTo = reportTo;
	}

	@Column(name = "remarks", nullable = false)
	public byte[] getRemarks() {
		return this.remarks;
	}

	public void setRemarks(byte[] remarks) {
		this.remarks = remarks;
	}

	@Column(name = "requestedVehicle", nullable = false, length = 10)
	public String getRequestedVehicle() {
		return this.requestedVehicle;
	}

	public void setRequestedVehicle(String requestedVehicle) {
		this.requestedVehicle = requestedVehicle;
	}

	@Column(name = "vehicleId", nullable = false, length = 36)
	public String getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "requisitionType", length = 10)
	public String getRequisitionType() {
		return this.requisitionType;
	}

	public void setRequisitionType(String requisitionType) {
		this.requisitionType = requisitionType;
	}

	@Column(name = "waterBottle", nullable = false, length = 11)
	public String getWaterBottle() {
		return this.waterBottle;
	}

	public void setWaterBottle(String waterBottle) {
		this.waterBottle = waterBottle;
	}

	@Column(name = "waterBottleAmount", nullable = false, length = 11)
	public String getWaterBottleAmount() {
		return this.waterBottleAmount;
	}

	public void setWaterBottleAmount(String waterBottleAmount) {
		this.waterBottleAmount = waterBottleAmount;
	}

	@Column(name = "simCard", nullable = false, length = 11)
	public String getSimCard() {
		return this.simCard;
	}

	public void setSimCard(String simCard) {
		this.simCard = simCard;
	}

	@Column(name = "simAmount", nullable = false, length = 11)
	public String getSimAmount() {
		return this.simAmount;
	}

	public void setSimAmount(String simAmount) {
		this.simAmount = simAmount;
	}

	@Column(name = "garland", nullable = false, length = 11)
	public String getGarland() {
		return this.garland;
	}

	public void setGarland(String garland) {
		this.garland = garland;
	}

	@Column(name = "garlandAmount", nullable = false, length = 11)
	public String getGarlandAmount() {
		return this.garlandAmount;
	}

	public void setGarlandAmount(String garlandAmount) {
		this.garlandAmount = garlandAmount;
	}

	@Column(name = "dropPlace", nullable = false, length = 100)
	public String getDropPlace() {
		return this.dropPlace;
	}

	public void setDropPlace(String dropPlace) {
		this.dropPlace = dropPlace;
	}

	@Column(name = "tourNo", nullable = false, length = 15)
	public String getTourNo() {
		return this.tourNo;
	}

	public void setTourNo(String tourNo) {
		this.tourNo = tourNo;
	}

	@Column(name = "recordOwner", nullable = false, length = 36)
	public String getRecordOwner() {
		return this.recordOwner;
	}

	public void setRecordOwner(String recordOwner) {
		this.recordOwner = recordOwner;
	}

	@Column(name = "TRconfirmationUuid", length = 36)
	public String getTrconfirmationUuid() {
		return this.trconfirmationUuid;
	}

	public void setTrconfirmationUuid(String trconfirmationUuid) {
		this.trconfirmationUuid = trconfirmationUuid;
	}

	@Column(name = "requestedMarketLabel", length = 100)
	public String getRequestedMarketLabel() {
		return this.requestedMarketLabel;
	}

	public void setRequestedMarketLabel(String requestedMarketLabel) {
		this.requestedMarketLabel = requestedMarketLabel;
	}

	@Column(name = "arrivalAirpot", length = 100)
	public String getArrivalAirpot() {
		return this.arrivalAirpot;
	}

	public void setArrivalAirpot(String arrivalAirpot) {
		this.arrivalAirpot = arrivalAirpot;
	}

	@Column(name = "departureAirport", length = 100)
	public String getDepartureAirport() {
		return this.departureAirport;
	}

	public void setDepartureAirport(String departureAirport) {
		this.departureAirport = departureAirport;
	}

	@Column(name = "estimatedTime")
	public Integer getEstimatedTime() {
		return this.estimatedTime;
	}

	public void setEstimatedTime(Integer estimatedTime) {
		this.estimatedTime = estimatedTime;
	}

	@Column(name = "reqStatus", length = 50)
	public String getReqStatus() {
		return this.reqStatus;
	}

	public void setReqStatus(String reqStatus) {
		this.reqStatus = reqStatus;
	}

	@Column(name = "parentId", length = 100)
	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Column(name = "splitBy", length = 100)
	public String getSplitBy() {
		return this.splitBy;
	}

	public void setSplitBy(String splitBy) {
		this.splitBy = splitBy;
	}

	@Override
	public String toString() {
		 try {
		        return new com.fasterxml.jackson.databind.ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(this);
		    } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
		        e.printStackTrace();
		    }
		    return null;
	}
	
	
}
